### ISSUE TITLE
KeyError when downloading the checkpoint on huggingface

### ISSUE THREAD

**Issue by tingxueronghua** [SALT-NLP/LLaVAR#14]
>>> from transformers import AutoModelForCausalLM
>>> model = AutoModelForCausalLM.from_pretrained("truehealth/LLaVar")
Downloading (…)lve/main/config.json: 100%|█████████| 857/857 [00:00<00:00, 64.2kB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/xxx/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 444, in from_pretrained                              
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/xxx/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 940, in from_pretrained                        
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/root/miniconda3/envs/xxx/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 655, in __getitem__                            
    raise KeyError(key)
KeyError: 'llava'

**Comment by StevenyzZhang** [comment]
Hi:
Have you correctly installed LLaVA (the version we provided in our subfolder)?

**Comment by tingxueronghua** [comment]
got it, thanks!
