### ISSUE TITLE
Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

### ISSUE THREAD

**Issue by aldrinc** [SALT-NLP/LLaVAR#6]
Merged Weights
https://huggingface.co/truehealth/LLaVar
<img width="497" alt="Screenshot 2023-07-20 at 1 02 04 PM" src="https://github.com/SALT-NLP/LLaVAR/assets/11620239/c9bad39e-9ac9-4482-aaf5-7d95782a61b6">

Startup Script
```
pip install --upgrade huggingface_hub
huggingface-cli login --token $HF_TOKEN
git clone https://github.com/SALT-NLP/LLaVAR
cd LLaVAR/LLaVA
pip install -e .
python -m llava.eval.run_llava \
    --model-name /workspace/llavar_v1 \
    --image-file "https://cdn.shopify.com/s/files/1/0057/3728/3618/products/a-man-called-otto_ezrjr0pm_480x.progressive.jpg" \
    --query "Who starred in the movie?"
```

Error
```
root@d38c96939557:/workspace/LLaVAR/LLaVA# python -m llava.eval.run_llava     --model-name /workspace/llavar_v1     --image-file "https://cdn.shopify.com/s/files/1/0057/3728/3618/products/a-man-called-otto_ezrjr0pm_480x.progressive.jpg"     --query "Who starred in the movie?"
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/LLaVAR/LLaVA/llava/eval/run_llava.py", line 148, in <module>
    eval_model(args)
  File "/workspace/LLaVAR/LLaVA/llava/eval/run_llava.py", line 58, in eval_model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 682, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1805, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 71, in __init__
    self.sp_model.Load(vocab_file)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
```

**Comment by StevenyzZhang** [comment]
Hi!

I downloaded the model checkpoint you are using and cannot reproduce the error. The checkpoint seems fine.

It seems this error is related to the checkpoint downloading according to [Issue 1 (in Chinese)](https://github.com/THUDM/ChatGLM-6B/issues/770) and [Issue 2 (in Chinese)](https://zhuanlan.zhihu.com/p/628389210).

I recommend using [this script](https://github.com/oobabooga/text-generation-webui/blob/main/download-model.py) to download the huggingface checkpoint.

**Comment by aldrinc** [comment]
@StevenyzZhang Works - thank you!
